import {createContext,useContext,useState,useEffect,type ReactNode} from 'react';import type {StudentState,Student,Attempt} from '../../types';import {readStudent,readStorage,saveStorage,STUDENT_KEY} from '../../lib/storage';import {createDemo,createLocal} from '../../data/progress';import {lessons} from '../../data/lessons';import {quizzes,gradeQuiz} from '../../data/quizzes';
interface StudentContext {state:StudentState;storageError:boolean;create:(student:Student)=>void;edit:(student:Student)=>void;restore:()=>void;favorite:(id:string)=>void;start:(id:string)=>void;complete:(id:string)=>void;toggleGoal:(id:string)=>void;submit:(quizId:string,answers:number[],attemptId:string)=>Attempt}
const Context=createContext<StudentContext|null>(null);
export function StudentProvider({children}:{children:ReactNode}){const [state,setState]=useState(()=>readStudent(readStorage(STUDENT_KEY)));const [storageError,setStorageError]=useState(false);
useEffect(()=>{setStorageError(!saveStorage(STUDENT_KEY,state))},[state]);
function complete(id:string){setState(s=>s.completed.includes(id)?s:{...s,completed:[...s.completed,id],activities:[{id:crypto.randomUUID(),text:`Concluiu ${lessons.find(l=>l.id===id)?.title??'uma aula'}`,date:new Date().toISOString()},...s.activities].slice(0,50)})}
function submit(quizId:string,answers:number[],attemptId:string){const quiz=quizzes.find(q=>q.id===quizId);if(!quiz)throw new Error('Quiz não encontrado');const attempt:Attempt={id:attemptId,quizId,answers:[...answers],score:gradeQuiz(quiz,answers),date:new Date().toISOString()};setState(s=>s.attempts.some(a=>a.id===attemptId)?s:{...s,attempts:[...s.attempts,attempt],activities:[{id:attemptId,text:`Concluiu quiz: ${lessons.find(l=>l.id===quiz.lessonId)?.title} (${attempt.score}/5)`,date:attempt.date},...s.activities].slice(0,50)});return attempt}
return <Context.Provider value={{state,storageError,create:student=>setState(createLocal(student)),edit:student=>setState(s=>({...s,student})),restore:()=>setState(createDemo()),favorite:id=>setState(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]})),start:id=>setState(s=>s.started.includes(id)?s:{...s,started:[...s.started,id]}),complete,toggleGoal:id=>setState(s=>({...s,goals:s.goals.map(g=>g.id===id?{...g,done:!g.done}:g)})),submit}}>{children}</Context.Provider>}
export function useStudent(){const ctx=useContext(Context);if(!ctx)throw new Error('StudentProvider ausente');return ctx}
