import type {ReactNode,ButtonHTMLAttributes} from 'react';import {Link} from 'react-router-dom';import {BookOpen,Plus,Info,Search,CheckCircle2} from 'lucide-react';
export function Logo(){return <Link to="/" className="logo" aria-label="Educa+, página inicial"><span className="logo-mark"><BookOpen size={25}/><span><Plus size={12} strokeWidth={4}/></span></span><span>Educa<span className="success">+</span></span></Link>}
export function Button({variant='',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:string}){return <button type="button" className={`btn ${variant} ${className}`} {...props}/>}
export function Action({to,children,secondary=false}:{to:string;children:ReactNode;secondary?:boolean}){return <Link className={`btn ${secondary?'secondary':''}`} to={to}>{children}</Link>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={`card ${className}`}>{children}</div>}
export function Badge({children}:{children:ReactNode}){return <span className="badge">{children}</span>}
export function Alert({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={`alert ${error?'error':''}`} role={error?'alert':'status'}><Info size={20}/><span>{children}</span></div>}
export function ProgressBar({value,label,color}:{value:number;label:string;color?:string}){return <div><div className="between small" style={{marginBottom:8}}><span>{label}</span><strong>{value}%</strong></div><div className="progress-track" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${value}%`,background:color}}/></div></div>}
export function ProgressRing({value,label}:{value:number;label:string}){return <div className="ring" role="img" aria-label={`${value}% ${label}`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" opacity=".2" strokeWidth="11"/><circle cx="60" cy="60" r="50" fill="none" stroke="var(--ring-color,#10b981)" strokeWidth="11" strokeLinecap="round" strokeDasharray={`${value*3.14159} 314.159`}/></svg><div className="ring-center"><strong>{value}%</strong><span className="small">{label}</span></div></div>}
export function EmptyState({title,text,children}:{title:string;text:string;children?:ReactNode}){return <Card className="empty"><Search size={36} className="brand-text"/><h3>{title}</h3><p className="muted">{text}</p>{children??<Action to="/app/biblioteca">Explorar aulas</Action>}</Card>}
export function Switch({label,checked,onChange,description}:{label:string;checked:boolean;onChange:()=>void;description?:string}){return <div className="switch-row"><div><strong>{label}</strong>{description&&<p className="muted small" style={{marginBottom:0}}>{description}</p>}</div><button className="switch" type="button" role="switch" aria-label={label} aria-checked={checked} onClick={onChange}><span className="switch-track"><span className="switch-knob"/></span></button></div>}
export function Toast({text}:{text:string}){return <div className="toast" role="status"><CheckCircle2 size={20}/>{text}</div>}
